-- ++++++++++++++++++++++++
-- < Mohamed Alaa >--
-- ++++++++++++++++++++++++


-- Q1
/*Find flights delayed due to abnormal weather conditions or other conditions 
and list the affected passengers*/
SELECT DISTINCT
	CONCAT(P.f_name, ' ', P.minit, ' ', P.l_name) AS 'Name',
    F.no AS 'Flight Number',
    F.from AS Departure,
    F.to AS Destination,
    F.departure AS 'Estimated Departure Time',
	WD.weather_condition AS WeatherConditions,
    WD.wind_speed,
    WD.wind_gust,
    WD.cloud_coverage,
    WD.relative_visibility,
    WD.precipitation,
	P.passport_no AS 'Affected Passenger Passport_no'
FROM
	flight F, book B, passenger P, weather_data WD, send S
WHERE
	F.status = 'E' 
	AND
	(WD.weather_condition LIKE '%Heavy%'
	OR WD.wind_gust > 30
	OR WD.wind_speed > 30
	OR WD.precipitation > 7
	OR WD.humidity < 15
	OR WD.relative_visibility < 5
	OR WD.cloud_coverage > 80)
    AND B.passport_no = P.passport_no AND B.flight_no=F.no AND S.weather_data_cd = WD.cd AND S.flight_no = F.no
GROUP BY 
	P.passport_no;
    
    
-- -----------------------------------------------------------------------------------------------------
-- Q2
/*List the total income generated by each airline considering ticket prices*/
SELECT 
    A.name AS 'Airline Name',
    SUM(T.price) AS 'Total Income'
FROM
    airline A,
    book B,
    flight F,
    ticket T
WHERE
    T.no = B.ticket_no
	AND B.flight_no = F.no
	AND F.airline_icao = A.icao
GROUP BY A.name;
-- -----------------------------------------------------------------------------------------------------

-- Q3
/*List Airline Names and their Average income*/
SELECT
    A.name AS 'Airline Name',
    AVG(T.price) AS 'Average Ticket Price'
FROM
    airline A
JOIN
    flight F ON A.icao = F.airline_icao
JOIN
    book B ON F.no = B.flight_no
JOIN
    ticket T ON B.ticket_no = T.no
GROUP BY
    A.name;
-- -----------------------------------------------------------------------------------------------------

-- Q4
/*Calculate Average Ticket Price per Class*/
SELECT
CASE
	WHEN 
		class IN ('B')
	THEN 
		'Bussinus'
	WHEN 
		class IN ('F')
	THEN 
		'First'
	WHEN 
		class IN ('E')
	THEN 
		'Economey'
END AS 'Class',
	AVG(T.price) AS 'Average Ticket Price Per Class'
FROM
	ticket T
GROUP BY
	T.class;
-- -----------------------------------------------------------------------------------------------------

-- Q5
/*Calculate the Average Salary per Job Title*/
SELECT
    E.job_title as 'Job Title',
    AVG(E.salary) AS 'Average Salary'
FROM
    employee E
GROUP BY
    E.job_title;
-- -----------------------------------------------------------------------------------------------------

-- Q6
/*Calculate the average delay time for flights, considering delay reasons (weather)*/
SELECT
    AVG((TIME(F.departure)-F.time)/3600) AS 'Average Delay Time'
FROM
    flight F
JOIN
    send S ON F.no = S.flight_no
JOIN
    weather_data WD ON S.weather_data_cd = WD.cd
WHERE
    F.status = 'E';
-- -----------------------------------------------------------------------------------------------------

-- Q7
/*Calculate the spending per passenger*/
SELECT
    P.passport_no as 'Passport Number', 
    CONCAT(P.f_name, ' ', P.minit, ' ', P.l_name) AS 'Name',
    T.price AS 'Average Spending'
FROM
    passenger P
JOIN
    book B ON P.passport_no = B.passport_no
JOIN
    ticket T ON B.ticket_no = T.no
GROUP BY
    P.passport_no;
-- -----------------------------------------------------------------------------------------------------

-- Q8
/*Calculate the percentage of on-time flights for each airline*/
SELECT
    A.icao AS 'Airline Icao',
    A.name AS 'Airline Name',
    COUNT(F.no) AS 'Total Flights',
    (COUNT(CASE WHEN F.status = 'O' THEN 1 END) / COUNT(F.No)) * 100 AS 'On Time Percentage'
FROM
    airline A
LEFT JOIN
    flight F ON A.icao = F.airline_icao
GROUP BY
    A.icao, A.name;
-- -----------------------------------------------------------------------------------------------------

-- Q9
/*List Bookings with Passport Details*/
SELECT
    B.book_date as 'Book Date',
    P.passport_no as 'Passport Number',
    B.flight_no as 'Flight Number',
    CONCAT(P.f_name, ' ', P.minit, ' ', P.l_name) AS 'Name'
FROM
    book B
JOIN
    passenger P ON B.passport_no = P.passport_no;
-- -----------------------------------------------------------------------------------------------------


-- Q10
/*Nationalities related to which languages*/
SELECT 
	CONCAT(f_name, ' ', minit, ' ', l_name) AS 'Name',
	nationality, 
CASE 
	WHEN
		nationality IN ('eygyptian','emirati','jordanian','qatari','saudi','tunisian')
	THEN
		'ar'
	WHEN 
		nationality IN ('garman','swiss')
	THEN
		'de'
	WHEN
		nationality IN ('french')
	THEN
		'fr'
	WHEN
		nationality IN ('turkish')
	THEN
		'tr'
	WHEN
		nationality IN ('american')
	THEN
		'en'
END AS 'Language'
FROM
	passenger P;
-- -----------------------------------------------------------------------------------------------------

    
-- Q11
/* Identify Flight Flight Duration*/
SELECT
    F.no AS 'Flight Number',
    F.departure,
    F.arrival,
    TIMESTAMPDIFF(SECOND, F.departure, F.arrival)/3600 AS 'Flight Duration in Hours'
FROM
    flight F
ORDER BY
    TIMESTAMPDIFF(SECOND, F.departure, F.arrival)/3600 DESC;	
-- -----------------------------------------------------------------------------------------------------

-- Q12
/*Identify the Most Popular Routes*/
SELECT
    F.from AS 'Departure Country',
    F.to AS 'Destination Country',
    COUNT(*) AS 'Flight Count'
FROM
    flight F
GROUP BY
    F.from, F.to
ORDER BY
    COUNT(*) DESC;
-- -----------------------------------------------------------------------------------------------------

-- Q13
/*List Most Passengers Nationalities*/
SELECT
    P.nationality,
    COUNT(*) AS 'Passenger Count'
FROM
    passenger P
GROUP BY
    P.nationality
ORDER BY
    COUNT(*) DESC;
-- -----------------------------------------------------------------------------------------------------

-- Q14
/*List Flights with the Most Unique Nationalities for each flight*/
SELECT
    F.no AS 'Flight Number',
    P.nationality,
    COUNT(DISTINCT P.nationality) AS 'Nationalities Number'
FROM
    flight F
JOIN
    book B ON F.no = B.flight_no
JOIN
    passenger P ON B.passport_no = P.passport_no
GROUP BY
    F.no
ORDER BY
    COUNT(DISTINCT P.nationality) DESC;
-- -----------------------------------------------------------------------------------------------------